<?php

$helper = $this->helper('HelloBrave\CookieCompliance\Helper\Data');
if ($helper->getConfig('hellobrave_cookiecompliance/general/enabled')) {
    $message = $helper->getConfig('hellobrave_cookiecompliance/general/message');
    $link_separator = $helper->getConfig('hellobrave_cookiecompliance/general/link_separator');
    $learn_link = $helper->getConfig('hellobrave_cookiecompliance/general/learn_link');
    $learn_message = $helper->getConfig('hellobrave_cookiecompliance/general/learn_message');
    $hide_message = $helper->getConfig('hellobrave_cookiecompliance/general/hide_message');
    $custom_css = $helper->getConfig('hellobrave_cookiecompliance/general/custom_css');

    $cookie_name = $helper->getConfig('hellobrave_cookiecompliance/advanced/cookie_name');
    $cookie_expire_days = $helper->getConfig('hellobrave_cookiecompliance/advanced/cookie_expire_days');
    $cookie_domain = $helper->getConfig('hellobrave_cookiecompliance/advanced/cookie_domain');
    $cookie_path = $helper->getConfig('hellobrave_cookiecompliance/advanced/cookie_path');
    $cookie_set_value = $helper->getConfig('hellobrave_cookiecompliance/advanced/cookie_set_value');

    $settings_raw = new stdClass();
    $settings_raw->expires = (int) $cookie_expire_days;
    $settings_raw->path = $cookie_path;

    if(strlen($cookie_domain) > 0) {
        $settings_raw->domain = $cookie_domain;
    }

    $json_settings = json_encode($settings_raw);

    ?>

    <div id="hb-cc-wrap">
        <span><?php echo $message; ?><?php echo $link_separator; ?><a href="<?php echo $learn_link; ?>" id="hb-cc-ll"><?php echo $learn_message; ?></a><?php echo $link_separator; ?><a href="#" id="hb-cc-hide"><?php echo $hide_message; ?></a></span>
    </div>
    <script type="text/javascript">
        requirejs(['jquery','jquery.cookie'],function(jQuery){
            (function($) {
                // Show cookie bar
                if ($.cookie('<?php echo $cookie_name; ?>') != "<?php echo $cookie_set_value; ?>") {
                    $('#hb-cc-wrap').show();
                }
                // Handle hide button
                $('#hb-cc-hide').click(function(event) {
                    event.preventDefault();
                    $('#hb-cc-wrap').hide();
                    // SET COOKIE
                    $.cookie('<?php echo $cookie_name; ?>', "<?php echo $cookie_set_value; ?>", <?php echo $json_settings; ?>);
                })
            })(jQuery);
        });
    </script>
    <?php if (strlen($custom_css) > 0) { ?>
    <style type="text/css">
        <?php echo $custom_css; ?>
    </style>
    <?php } ?>
<?php

} ?>
